### PR TITLE
Add Headers middleware and options

### PR DESCRIPTION
**Pull request by andrewlock**
Allows sending headers with the file/directory response.
Addresses #18

### CODE REVIEW

**Comment by andrewlock** [comment]
Very frustratingly, I can't get the `HeadersTests` to pass. There's something strange going on there - the underlying exception thrown is `The server returned an invalid or unrecognized response` which is frustratingly generic. 

Even worse, this _only_ happens when using the `dotnet-serve` process started in the tests. If I explicitly start the process _outside_ the tests, and point the test client at it, the tests pass!

I've tried debugging right into the corefx source, but I can't see what's wrong. As far as I can see it's throwing [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L875), but as I say, _only_ when in the process started by the tests. I'm basically out of ideas here 🙁 

Don't suppose you have any ideas @natemcmaster? Have you seen anything like this before?

**Comment by natemcmaster** [comment]
I haven’t seen this error before. I wonder if HttpClient doesn’t like these headers in particular. Maybe try different test headers?

**Comment by andrewlock** [comment]
Doh 🙁 it's very odd, and doesn't seem to be specific to these headers.. I'll play some more and see if I can get to the bottom of it tomorrow.

> If I explicitly start the process outside the tests, and point the test client at it, the tests pass!

This is the really odd bit! 🤔

**Comment by andrewlock** [comment]
Surprise surprise, I was being an idiot 🙄. I'd explicitly added quotes around the header values in the test suite. That's unnecessary as you're already quoting the arguments, so the quotes ended up as escaped values in the header itself. i.e. the header name set in the response was `\"X-XSS-Protection`. 

It wasn't happening when running manually, because I was using the right arguments then! All good now though 🙂

**Comment by natemcmaster** [comment]
Awesome, thanks for the contribution!

**Pull request merged**
